services:
  db:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: ZopChatDb
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080